#!/usr/bin/zsh
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export LESSHISTFILE="-"
export EDITOR='nvim'
export BLOCKSIZE='MiB'
export TERMINAL='alacritty'
export WALLPAPER=$HOME/Pictures/wallpapers/City_Bridge.jpg
export ELINKS_CONFDIR="$XDG_CONFIG_HOME"/elinks
export BROWSER='firefox'
export PYTHONSTARTUP="$XDG_CONFIG_HOME"/python/startup.py
export IPYTHONDIR="$XDG_CONFIG_HOME"/jupyter
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEAuthority
export TEXMFHOME=$XDG_DATA_HOME/texmf
export TEXMFVAR=$XDG_CACHE_HOME/texlive/texmf-var
export TEXMFCONFIG=$XDG_CONFIG_HOME/texlive/texmf-config
export RXVT_SOCKET="$XDG_RUNTIME_DIR"/urxvtd
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export RANDFILE=$XDG_DATA_HOME/rnd
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export XAUTHORITY="$XDG_DATA_HOME"/xorg/Xauthority
export XINITRC="$XDG_CONFIG_HOME"/x11/xinitrc
export PLTUSERHOME="$XDG_DATA_HOME"/racket 
export HISTFILE="$XDG_DATA_HOME"/shell/bash_history
export PAGER='less'
export MAXIMA_USERDIR="$XDG_CONFIG_HOME"/maxima
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export XCOMPOSEFILE="$XDG_CONFIG_HOME/x11/xcompose"
export XCOMPOSEFILE="$XDG_CACHE_HOME/x11/xcompose"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
#haskell variables
export STACK_ROOT="$XDG_DATA_HOME"/stack
export QT_QPA_PLATFORMTHEME=gtk2

# octave
export OCTAVE_HISTFILE="$XDG_CACHE_HOME/octave-hsts"
export OCTAVE_SITE_INITFILE="$XDG_CONFIG_HOME/octave/octaverc"

#CUDA
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv

#ruby
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle
export GEM_HOME="$XDG_DATA_HOME"/gem
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem

# nuget C#
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages

# rust
export CARGO_HOME="$XDG_DATA_HOME"/cargo \
	RUSTUP_HOME="$XDG_DATA_HOME"/rustup

# ocaml - partial
export OPAMROOT="$XDG_DATA_HOME/opam"

# virt
export LIBVIRT_DEFAULT_URI="qemu:///system"
