#!/usr/bin/zsh

# xdg
export XDG_CONFIG_HOME="$HOME/.config" \
       XDG_DATA_HOME="$HOME/.local/share" \
       XDG_CACHE_HOME="$HOME/.cache"

# system utilities
export LESSHISTFILE="-" \
       PAGER='less' \
       BLOCKSIZE='MiB' \
       INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc \
       WGETRC="$XDG_CONFIG_HOME"/wget/wgetrc \
       RANDFILE=$XDG_DATA_HOME/rnd \
       GNUPGHOME="$XDG_DATA_HOME"/gnupg \
       ELINKS_CONFDIR="$XDG_CONFIG_HOME"/elinks \
       RXVT_SOCKET="$XDG_RUNTIME_DIR"/urxvtd \
       HISTFILE="$XDG_DATA_HOME"/shell/bash_history \
       ZDOTDIR="$XDG_CONFIG_HOME/zsh" \
       WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default

## x11
export XINITRC="$XDG_CONFIG_HOME"/x11/xinitrc \
       XAUTHORITY="$XDG_DATA_HOME"/xorg/Xauthority \
       ICEAUTHORITY="$XDG_CACHE_HOME"/ICEAuthority \
       XCOMPOSEFILE="$XDG_CONFIG_HOME"/x11/xcompose \
       XCOMPOSECACHE="$XDG_CACHE_HOME"/x11/xcompose

## themes
export QT_QPA_PLATFORMTHEME=gtk2 \
       GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc \

# personal
export EDITOR='nvim' \
       TERMINAL='alacritty' \
       BROWSER='firefox' \
       PRIVATE_BROWSER='firefox --private-window' \
       WALLPAPER="$(xdg-user-dir PICTURES)"/wallpapers/City_Bridge.jpg \
       JOURNAL_DIRECTORY="$HOME/Journals" \
       GRIM_DEFAULT_DIR="$(xdg-user-dir PICTURES)"/saved

# python
export PYTHONSTARTUP="$XDG_CONFIG_HOME"/python/startup.py \
       IPYTHONDIR="$XDG_CONFIG_HOME"/jupyter \
       JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter \
       PYTHONDONTWRITEBYTECODE=1

# tex
export TEXMFHOME=$XDG_DATA_HOME/texmf \
       TEXMFVAR=$XDG_CACHE_HOME/texlive/texmf-var \
       TEXMFCONFIG=$XDG_CONFIG_HOME/texlive/texmf-config

# CUDA
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv

# virt
export LIBVIRT_DEFAULT_URI="qemu:///system"

# docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker \
       MACHINE_STORAGE_PATH="$XDG_DATA_HOME"/docker-machine

export XCURSOR_THEME=Catppuccin-Mocha-Dark-Cursors \
       XCURSOR_SIZE=32
