#!/bin/sh

USERXSESSION="$XDG_CACHE_HOME/x11/xsession"
USERXSESSIONRC="$XDG_CACHE_HOME/x11/xsessionrc"
ALTUSERXSESSION="$XDG_CACHE_HOME/x11/Xsession"
ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"

xrdb -merge "$XDG_CONFIG_HOME"/x11/xdefaults
feh --bg-fill --no-fehbg "$WALLPAPER" &

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
systemctl --user restart emacs

picom &
unclutter &
copyq &
#exec herbstluftwm --locked
exec qtile start
